name: decorizer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependency_overrides:
  win32: 5.5.5
  archive: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  #dart
  meta: ^1.15.0
  equatable: ^2.0.5

  #data
  shared_preferences: ^2.3.2

  #architecture
  get: ^4.6.6

  #ui - resource
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3

  #ui - widget
  nav: ^1.4.3
  simple_shadow: ^0.3.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  lottie: ^3.1.2


  #network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  pusher_channels_flutter: ^2.5.0

  #maps
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  google_maps_flutter_android: ^2.5.1
  google_maps_flutter_platform_interface: ^2.2.6

  #firebase and notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  #other
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  path: ^1.9.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  dartz: ^0.10.1
  flutter_html: ^3.0.0-beta.2
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.3
  dotted_border: ^2.1.0
  injectable: ^2.5.0
  flutter_otp_text_field: ^1.4.0+2
  readmore: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  flutter_image_compress: ^2.4.0
  carousel_slider: ^5.0.0
  image_gallery_saver_plus: ^4.0.1
  crypto: ^3.0.6

  #app specific settings
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  change_app_package_name: ^1.3.0
  infinite_scroll_pagination: ^4.0.0
  flutter_rating_bar: ^4.0.1
  # image_gallery_saver: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner:
  json_serializable: ^6.8.0
  injectable_generator:

  flutter_oss_licenses: ^3.0.2

flutter_gen:
  output: lib/common/resources/gen
  #  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/map/
    - assets/animations/
    - assets/image/svg/
    - assets/image/png/
    - assets/image/flag/
    - assets/translations/
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 100
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 500
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 300
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 400
        - asset: assets/fonts/IBM-Medium.ttf
          weight: 100


flutter_native_splash:

  color: "#000000"
  image: assets/image/png/app_icon.png

  android_12:
    color: "#000000"
    image: assets/image/png/app_icon.png
    icon_background_color: "#000000"


  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_foreground: "assets/image/png/app_icon.png"
  adaptive_icon_background: "#000000"
  min_sdk_android: 24
  image_path: "assets/image/png/app_icon.png"
  adaptive_icon_padding: true

  fonts:
    - family: roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
